version: '3.8'
services:
  instructor-embedding-api:
    image: ghcr.io/stl314159/instructor-embedding-api:latest
    command: python ./index.py
    volumes:
      - ${VOLUME}:/root/.cache/torch/
    ports:
      - ${PORT}:5000
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ['${DEVICE}']
              capabilities: [gpu]
